export const HOME_PAGE_RENDERED = 'HOME_PAGE_RENDERED';

export const RECIPE_HINT_FAILED = 'RECIPE_HINT_FAILED';
export const RECIPE_HINT_LOADING = 'RECIPE_HINT_LOADING';
export const RECIPE_HINT_RECEIVED = 'RECIPE_HINT_RECEIVED';
